### ISSUE TITLE
64bit OS + 32bit EXE だと 32bit だと判定される

### ISSUE THREAD

**Issue by koron** [koron/go-arch#1]
https://github.com/koron/netupvim/issues/28 より

> PROCESSOR_ARCHITECTURE ですが、OSが64bitでも、
> 実行したプロセスが32bitだと x86 が設定されます。
> 64bit OSで32bitプロセスを実行した場合には、
> 代わりに PROCESSOR_ARCHITEW6432 に AMD64 が設定されます。

**Comment by k-takata** [comment]
参考: https://msdn.microsoft.com/ja-jp/library/aa384274.aspx

**Comment by koron** [comment]
修正自体はできてて、テスト追加中～

**Comment by koron** [comment]
治ったはず。
